USE MYFIRST_DB;
GO




CREATE TABLE EMPLOYEE (
    SSN CHAR(11) NOT NULL,
    First_name VARCHAR(20) NOT NULL,
    Last_name VARCHAR(20) NOT NULL,
    birth_date DATE,
    gender CHAR(1) NOT NULL,
	CONSTRAINT PK_employee PRIMARY KEY (SSN)
);
SELECT * 
FROM EMPLOYEE

CREATE TABLE DEPARTEMENT(
  D_number CHAR(11) NOT NULL,
  D_name VARCHAR(50) NOT NULL,
  hiring_date Date,
  Mgr_SSN CHAR(11) NOT NULL,
  CONSTRAINT PK_departement PRIMARY KEY (D_number),
  CONSTRAINT FK_dep_emp FOREIGN KEY (Mgr_SSN) REFERENCES EMPLOYEE(SSN)
);

SELECT * 
FROM DEPARTEMENT


ALTER TABLE EMPLOYEE 
ADD D_num CHAR(11) NOT NULL;

ALTER TABLE EMPLOYEE 
ADD super_SSN CHAR(11) NOT NULL;

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_emp_dep FOREIGN KEY (D_num) REFERENCES DEPARTEMENT(D_number);

ALTER TABLE EMPLOYEE 
ADD CONSTRAINT FK_emp_emp FOREIGN KEY (super_SSN) REFERENCES EMPLOYEE(SSN);

CREATE TABLE Dependent(
  D_num CHAR(11) NOT NULL,
  dep_SSN CHAR(11) NOT NULL,
  Gender VARCHAR(10) NOT NULL,
  Birth_date Date,
  CONSTRAINT PK_dependent PRIMARY KEY (D_num, dep_SSN),
  CONSTRAINT FK_dependent FOREIGN KEY (dep_SSN) REFERENCES EMPLOYEE(SSN)
);


CREATE TABLE Department_Location(
  D_number CHAR(11) NOT NULL,
  Location VARCHAR(15) NOT NULL,
  CONSTRAINT PK_dep_loc PRIMARY KEY (D_number, Location),
  CONSTRAINT FK_dep_loc FOREIGN KEY (D_number) REFERENCES DEPARTEMENT(D_number)
);


CREATE TABLE Project(
  Pnumber CHAR(11) NOT NULL,
  Pname VARCHAR(15) NOT NULL,
  City VARCHAR(15) NOT NULL,
  Location VARCHAR(15) NOT NULL,
  D_number CHAR(11) NOT NULL,
  CONSTRAINT PK_pro PRIMARY KEY (Pnumber),
  CONSTRAINT FK_pro FOREIGN KEY (D_number) REFERENCES DEPARTEMENT(D_number)
);


CREATE TABLE Employee_Project(
  Pnumber CHAR(11) NOT NULL,
  SSN CHAR(11) NOT NULL,
  Working_hours VARCHAR(15) NOT NULL,
  CONSTRAINT PK_pro_emp PRIMARY KEY (Pnumber,SSN),
  CONSTRAINT FK_project FOREIGN KEY (Pnumber) REFERENCES Project(Pnumber),
  CONSTRAINT FK_employee FOREIGN KEY (SSN) REFERENCES EMPLOYEE(SSN)
);






